### ISSUE TITLE
How to filter data?

### ISSUE THREAD

**Issue by syedhamidali** [cghoffmann/mjoindices#4]
Hi,
I want to filter the daily OLR data, and I need to see a particularly few days, e.g., from 2021-May-01 to 2021-May-30. How would I do that using this library, and what should I keep in mind so that I would make sure that the data is MJO Filtered?

**Comment by cghoffmann** [comment]
Hi,

I am not sure if I really understand the question. Partiulary what you exactly mean with "filtering". 

Do you want to see the OMI values? Then you should find everything you need in the [examples ](https://github.com/cghoffmann/mjoindices/blob/master/examples/recalculate_original_omi.py)

Do you only want to apply a Wheeler-Kiladis-Filtering? This is probabaly implicitely included in the package but not officially supported and fully tested and we would have to think about it...

Cheers,
Christoph.

P.S.: Since this is not an issue of the software itself, I will set it to "invalid" and close it in the near future. Next time, please use the discussion page for reqeust like this.

**Comment by syedhamidali** [comment]
I did it; I wanted to filter the OLR data. I am not sure if I am right or wrong. I read a few papers saying before the time of cyclone, OLR anomaly was negative (7 days average), and the same OLR anomaly data was MJO filtered. Now that MJO filtered means the phase of MJO, which varies from 20 to 100 days.
**How I did it?**
import scipy
from scipy.signal import filtfilt, butter, lfilter
def butterfilt(data,lowcut, highcut, fs, order=2):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    y = scipy.signal.filtfilt(b, a, data)
    return xr.DataArray(y,coords=data.coords,dims=data.dims)

where the frequency is 1, low cut is 1/100, and highcut is 1/20

![image](https://user-images.githubusercontent.com/35923822/151768448-76a1006d-8ce1-4b74-841a-30d951e0d872.png)

If you can confirm if this is the correct method, it  would be highly appreciable,
Thanks,
Syed

**Comment by cghoffmann** [comment]
Hi Syed,

I think, it depends on your research question, which kind of filtering is appropiate or how complicated is has to be. So, I cannot definitively answer yes or now here.

It seems that you are just performing a temporal filtering here. 

The filtering, which is used to identify the MJO in OLR data to get the OMI index, is a temporal AND spatial filtering that leads to a somewhat lengthy code. As I said, it is included in the package and can be executed separately. But we have not tested it for all combinations of possible filtering paramters, since we only need special configiurations. So I cannot promise to support this here in detail. The respective module is this one, and you can import it after installing the packge: [](https://github.com/cghoffmann/mjoindices/blob/master/src/mjoindices/omi/wheeler_kiladis_mjo_filter.py).

Maybe our [paper ](http://doi.org/10.5334/jors.331) on the package could be helpful, particulary the references therein.

Furthermore, the following paper tells you probably more about the technique: [](https://doi.org/10.1175/1520-0469(1999)056<0374:CCEWAO>2.0.CO;2)

But as I said in the beginning: depending on your goal your type of filtering might also be enough...

Cheers,
Christoph.
