### ISSUE TITLE
Calculating OMI for model output

### ISSUE THREAD

**Issue by sweidy** [cghoffmann/mjoindices#5]
Thank you for making this code accessible - I found it really helpful in starting a project on the MJO! 

I've been using this package to calculate the OMI for simulated model output, and I ran into complications with numpy's default calendar capabilities. For at least the GCM that I am using (SPCAM), the model output uses a nonstandard calendar (no leap years, with years from 0001 and on), which I think is the case for many GCMs. Unfortunately, numpy and pandas only support time variables for a standard calendar that includes leap years, from ~1600 AD onwards. 

I was able to modify the module to avoid leap years, but my methods are a bit hacky and I'm not completely sure that they work correctly yet (I still need to run some sanity checks). I wanted to put this on your radar, if it wasn't already - I'd be happy to share with you the changes that I made if that sounds helpful.

**Comment by cghoffmann** [comment]
Hi,

ok, that's a good point, which wasn't actually on my radar...

Currently, I am working on some other things. But of course I keep on collecting improvements for the next versions. So, I would be happy if you share your improvements and would maybe include them in the medium term. Of course, it would be very helpful if you could still perform the missing tests etc. 

By the way: I have another problem in the context of model data in my mind, which came up after the publication: Using long-term OLR data (like 100 years or so) to calculate the EOFs could lead to memory problems. Did you come across something like this? In any case, I am interested in you experience, since we are not working ourselves with GCMs extensively. 

Cheers,
Christoph.

**Comment by sweidy** [comment]
Hi Christoph, 

No worries. I will work through my code more carefully and clean up the changes I made to make sure whatever I changed makes sense. I'll let you know when I have something presentable. 

I haven't run into memory issues yet, but this is because I am currently only using ~10 years of model output as a first pass. I think in the future I was planning on using 30 or 40 years of data at a time and increasing the sample size by using multiple 40-year ensembles. A different set of EOFs would be calculated from each 40-year ensemble member. It requires a lot of computation power to run a model for 100 years (and that much data makes other analyses computationally difficult too) so I don't think I would try to use 100 years at once. However, it's possible that other people would want that kind of information, and I'm just not aware of all the use cases! 

Thanks for your help,
Sarah

**Comment by cghoffmann** [comment]
Hi Sarah,

this sounds good! Are you familiar with the GitHub workflow for contributions? A good way is to fork this repository, make your changes in your own forked repo and then create a pull request here. This makes it quite simple for me to review the changes and directly integrate them.

Regarding the memory issues: I tried to use the long model runs of CMIP6 myself. But the problems came up on a simple workstation. I will also try an HPC system with a lot more memory. In the long-term, it might be of interest to parallelize the code. But this does not seem to be straightforward and I will collect modelers' opinions before. So I am glad that the package seems to be useful for you (almost) as it is.

Looking forward to your contributions,
Christoph.

**Comment by sweidy** [comment]
Thanks Christoph - I am not familiar with github workflow but I will try out making a fork with the changes I made! 

Best,
Sarah

**Comment by sweidy** [comment]
Hi Christoph, 

I'm currently working on a branch called no_leap in my fork. From testing, it looks like my current issue is that the calculated PCs for Dec 31 don't match up to Jan 1 of the next year (this becomes obvious when plotting OMI phase diagrams). I'm continuing to double check my work, but do you have an intuition for where this issue would come from,  such as the original EOF calculation or from the PCs themselves? Either way, I'll keep cleaning the code up!

Thanks,
Sarah

**Comment by cghoffmann** [comment]
Hi Sarah,

without knowing exactly what happens in your version, this sounds like something, which can also be encountered in my original code.

Without writing too much, I'll first refer to the comments of the following function: https://github.com/cghoffmann/mjoindices/blob/eba83a8004860a2a090919cf5a1941a5940efd84/src/mjoindices/tools.py#L53

The basic point is that the EOFs are calculated for a paticular DOY-window and the composition of the window may change depending on if you are working with a leap year or not and how you calculate the window bounds. I'm not sure, how this shows up when you are working on a version, which has no leap years at all...

The usage of strict_leap_year_treatment=True in my version also resulted in spikes in the PCs at the end of the years, because the EOFs did not transition smoothly from Dec 31 to Jan 1. I this this is also at leasdt mentioned in our correspondig paper: http://doi.org/10.5334/jors.331

That's all I can contribute for the moment and hope that you are able to figure this out...

Best,
Christoph.

**Comment by sweidy** [comment]
Hi Christoph, 

I went down a bit of a rabbit hole trying to figure out how to guarantee continuity across December to January, but I finally finished updating this fork. I've updated the src functions, as well as added a few test cases and updated the example files (for recalculate_original_omi). The most important changes are that now many of the functions take a no_leap parameter, which will tell the code whether to treat the dataset as having leap years or not. Other than adding the parameter to calc_eofs_from_olr, most of the changes are under the hood and shouldn't change the user end of the package much. 

For guaranteeing continuity across December to January, we might have found a nice solution - I will share it with you once it is in a shareable form!

Best,
Sarah

**Comment by cghoffmann** [comment]
Hi Sarah,

sorry for the late reply. I'm glad that you are still working on this!

I am not sure if I understood you correctly: Is there already a bit of code that I should look at now or are you still working on a shareable form of this code? 

I any case, the best way to compare and integrate your changes is a pull request, which you can create in my original repository. Then I can easily review the code and integrate it. However, I think I will not be able to to this before August or so. So, take your time for the improvements.

And we probably have to discuss to what extent your solution changes the original OMI algorithm and output. So far, the package claims to be very close to the original Kiladis version. Changes in the algorithm would also have to be scientifically evaluated and maybe published with a comparison to the original. Maybe we should discuss this via email and also include some OMI experts after I saw your code. In any case, I think it is important to have a clear switch in the code, which allows for producing the original OMI version (probably as the default) until a scientific evaluation is available to the public (and probaly also later on).

Best,
Christoph.

**Comment by cghoffmann** [comment]
Solutions to the issues raised here have been included in the release 1.4.0 in cooperation with @sweidy . Thanks a lot!
